version: '3'
services:
  ml_service:
    build: ./ML_service
    container_name: ml_service
    ports:
      - "5221:5221"
    networks:
      - ml_network

  tg_bot:
    build: ./TG_bot
    container_name: tg_bot
    networks:
      - ml_network
    depends_on:
      - ml_service

networks:
  ml_network:
    driver: bridge
